language: scala
jdk: oraclejdk7
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2



script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile

scala:
  - 2.11.2
